export interface UserAchievement {
  title: string
  description: string
  isAutoGenerated: boolean
}

export const fetchUserAchievements = async (userId: number): Promise<UserAchievement[]> => {
  const res = await fetch(`http://localhost:5000/api/Achievements/user/${userId}`)
  if (!res.ok) throw new Error("Failed to fetch achievements")
  return res.json()
}
