export interface UserAchievement {
  achievementId: number;
  title: string;
  description: string;
  isAutoGenerated: boolean;
  points: number;
}

export interface FullAchievement extends UserAchievement {
  userId: number;
  sportType: string;
}

export interface CreateAchievementRequest {
  title: string;
  description: string;
  isAutoGenerated: boolean;
  sportType: string;
  points: number;
}

export interface AssignAchievementRequest {
  userId: number;
  achievementId: number;
  eventId: number | null;
  awardedByUserId: number;
}

