import { useEffect, useState } from 'react'
import { UserAchievement, fetchUserAchievements } from '../services/api'

const AdminDashboard = () => {
  const [achievements, setAchievements] = useState<UserAchievement[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const loadAchievements = async () => {
      try {
        const data = await fetchUserAchievements(1) // User ID 1 for now
        console.log("✔ Achievements fetched:", data)
        console.log("✔ Fetched Achievements", data, Array.isArray(data))

        setAchievements(data)
      } catch (err) {
        console.error("❌ Error loading achievements:", err)
      } finally {
        setLoading(false)
      }
    }

    loadAchievements()
  }, [])

  console.log("🏁 Final Achievements state:", achievements)

  return (
    
    <div style={{ padding: '2rem', color: 'white', textAlign: 'center' }}>
      <h1>📋 Admin Dashboard</h1>
      <h2 style={{ marginTop: '2rem' }}>User Achievements</h2>

      {loading ? (
        <p>Loading achievements...</p>
      ) : achievements.length === 0 ? (
        <p>❌ No achievements found for user 1.</p>
      ) : (
        <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '1rem' }}>
          {achievements.map((ach, idx) => (
            <div
              key={idx}
              style={{
                backgroundColor: '#2c2c2c',
                padding: '1rem',
                borderRadius: '8px',
                width: '280px',
                boxShadow: '0 0 10px rgba(0,0,0,0.3)',
              }}
            >
              <h3>{ach.title}</h3>
              <p>{ach.description}</p>
              <p style={{ color: ach.isAutoGenerated ? 'lightgreen' : 'skyblue' }}>
                {ach.isAutoGenerated ? 'Auto Achievement' : 'Admin Assigned'}
              </p>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export default AdminDashboard



